# ByteProxy Documentation - Jekyll Configuration

# Site Settings
title: ByteProxy
description: Extensible web proxy for Discord, GitHub, and other APIs
baseurl: ""
url: ""
repository: ByteBrushStudios/Proxy

# Theme settings
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

# Just the Docs settings
aux_links:
  "ByteProxy on GitHub":
    - "https://github.com/ByteBrushStudios/Proxy"
  "Discord Community":
    - "https://discord.gg/Vv2bdC44Ge"

# Enable search
search_enabled: true

# Footer content
footer_content: "Copyright &copy; 2025 ByteBrush Studios. Distributed under AGPL-3.0 license."

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:path/
  
# Default front matter
defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: default
      nav_order: 1
